name: Release

on:
  push:
    tags: [ 'v*' ]

permissions:
  contents: write

jobs:
  build-and-release:
    name: Build and release
    strategy:
      matrix:
        node: [ lts/* ]
        os: [ ubuntu-latest ]
      fail-fast: false
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: generate changelog
        run: |
          echo "## What's Changed" >> CHANGELOG.md
          git log --pretty=format:'- %s by @%an' --grep '^(. )?(fix|feat|perf|sync)(\(.+\))?:' -E $(git describe --tags --abbrev=0 ${{ github.ref_name }}^)..${{ github.ref_name }} >> CHANGELOG.md
          echo -e '\n\n**Full Changelog**: https://github.com/${{ github.repository }}/compare/'$(git describe --tags --abbrev=0 ${{ github.ref_name }}^)'...${{ github.ref_name }}' >> CHANGELOG.md
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies and build
        run: |
          npm install
          npm run build
          cp LICENSE dist/LICENSE
          mkdir plugin
          mkdir plugin/hook-vue
          mv dist/* plugin/hook-vue
      - uses: TheDoctor0/zip-release@0.7.6
        with:
          directory: plugin
          filename: 'hook-vue-${{ github.ref_name }}.zip'
      - uses: ncipollo/release-action@v1
        with:
          artifacts: 'plugin/hook-vue-${{ github.ref_name }}.zip'
          bodyFile: 'CHANGELOG.md'
